version: "3"
services:
  logstash-shipper:
    image: docker.elastic.co/logstash/logstash-oss:6.3.1
    volumes:
      - ./configs/logstash/shipper/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.40.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "logstash:1:1"
    depends_on:
      - zookeeper
  logstash-indexer:
    image: docker.elastic.co/logstash/logstash-oss:6.3.1
    volumes:
      - ./configs/logstash/indexer/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.1
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.1
    ports:
      - 5601:5601
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/16
